name: Build and Push Docker image

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set version tag
      id: vars
      run: |
        DATE_TAG=$(date +'%Y%m%d')
        # Find the number of builds for today; GITHUB_RUN_NUMBER is unique per workflow, but you may want continuity across the repo
        BUILD_NUMBER=$( (git tag --list "${DATE_TAG}-*" | wc -l) || echo "0" )
        BUILD_NUMBER=$((BUILD_NUMBER + 1))
        VERSION_TAG="${DATE_TAG}-${BUILD_NUMBER}"
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
        echo "::set-output name=version::$VERSION_TAG"
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version }}
